### ISSUE TITLE
Add support for 'include'

### ISSUE THREAD

**Issue by Mitica** [sirlantis/liquid-node#24]
It is posible to implement 'include' tag like in Ruby Liquid?

**Comment by thardy** [comment]
I would love to see include capability in liquid-node as well, or some other reusable template-within-template capability.

**Comment by dheniges** [comment]
+1 to this. Any particular challenges getting this in liquid-node? I'm assuming there's a reason the grunt task is registering the `include` tag rather than having it in this library?

**Comment by sirlantis** [comment]
The main reason is that when I built this library (some years ago) the `include`-tag didn't exist in the Ruby implementation.

But you are right that this should be added here now as well. I currently don't have the time for it though.

What is important however that it SHOULD expose a hook to change from where to include the data from (Ruby does so as well).

**Comment by dheniges** [comment]
I'm taking a crack at porting over the include from `grunt-liquid`, but I'm failing to see where this `template.engine.importer` is defined: https://github.com/sirlantis/grunt-liquid/blob/master/src/lib/liquid-ext.coffee#L55

It looks like it's just loading the file and calling extParse with the contents. What's providing that `importer` function though?

**Comment by sirlantis** [comment]
It's done in https://github.com/sirlantis/grunt-liquid/blob/417cc93c9a7724d3ab76ed5bf02141de311dada3/src/index.coffee#L28 because that part relies on the Grunt filesystem API and the `liquid-ext.coffee` already tries to be framework/context agnostic (the same code file is used in `assemble-liquid`).

**Comment by sirlantis** [comment]
But I assume the future-proof approach would be to convert the [original ruby implementation](https://github.com/Shopify/liquid/blob/master/lib/liquid/tags/include.rb) to CoffeeScript. The syntax translates quite well (with the exception of arrays and of course liquid-nodes requirement to use promises). It relies on a "FileSystem" adapter that can be accessed via `context.registers[:file_system]`.

**Comment by imjoshholloway** [comment]
I've started work on an include implementation: https://github.com/imjoshholloway/liquid-node/tree/feature-include

It's very basic at the minute. I've added the ability to optionally pass in a instance of `Liquid.LocalFileSystem` to the `Liquid.Engine` which is used within the include tag constructor to load the file.

For example:

```javascript
var engine = new Liquid.Engine(new Liquid.LocalFileSystem("./views", "html"));
```

This gives you access to a `engine.readTemplateFromFile('template/name')` method which resolves a promise with the file source.

For the include tag itself I've actually just got a simplified version of the one used in [assemble-liquid](https://github.com/sirlantis/assemble-liquid/blob/master/src/liquid-ext.coffee#L42-L62)

Before I go to much further is there any feedback on the initial implementation?

**Comment by sirlantis** [comment]
I really like it! :+1:

**Comment by sirlantis** [comment]
I added a few comments to the code.

**Comment by imjoshholloway** [comment]
@sirlantis thanks for the feedback. I've swapped out the stuff you suggested. Your point about the `Liquid.NullFileSystem` actually closely follows the actually Ruby implementation so I've created a `Liquid.BlankFileSystem` class which each `FileSystem` would then be expected to extend.

So the updated API for this is would be:

```javascript

var engine = new Liquid.Engine();

engine.fileSystem // Currently an instance of Liquid.BlankFileSystem

engine.fileSystem.readTemplateFile('index').catch(function (err) {
  console.log(err.message) // "This file system doesn't allow includes"
});

engine.registerFileSystem(new Liquid.LocalFileSystem("./views"));

engine.fileSystem.readTemplateFile('index').then(function (src) {
  console.log(src); // `src` being whatever was in ./views/index.html
});
```

Some notable things that this currently lacks vs the Ruby implementation is caching but I'm going to look at that shortly.

**Comment by reggi** [comment]
@imjoshholloway Looking at your implementation now, and I really like it. Just to clarify, the `src` within the `then()` is raw unparsed liquid, essentially a giant rendering of the `index` file with concatenated `{% include "file" %}` statements?

```javascript
engine.fileSystem.readTemplateFile('index').then(function(src){
  
})
```

for instance I have a file `index.liquid`

```liquid
{% assign greeting = "Hello" %}
{{ greeting }} World!
{% include "foo" %}
```

and `foo.liquid`

```liquid
FOO BAR, {{ greeting }}
```

Ideally `src` would be:

```liquid
{% assign greeting = "Hello" %}
{{ greeting }} World!
FOO BAR, {{ greeting }}
```

**Comment by imjoshholloway** [comment]
@reggi the result from `readTemplateFile('index')` would in fact be the unparsed file. The `readTemplateFile` method simple loads the file from the file system:

```coffeescript
readTemplateFile: (templatePath) ->
    @fullPath(templatePath)
      .then (fullPath) ->
        Fs.readFileAsync(fullPath, 'utf8')
          .catch (err) ->
            throw new Liquid.FileSystemError "Error loading template: #{err.message}"
```

An example usage would be:

```javascript

var engine = new Liquid.Engine();
engine.registerFileSystem(new Liquid.LocalFileSystem("./views"));

engine.fileSystem.readTemplateFile('index').then(function (src) {
  var context = {};
  return engine.parseAndRender(src, context);
});
```

**Comment by reggi** [comment]
Thanks for the detailed explanation @imjoshholloway! :+1:

**Comment by imjoshholloway** [comment]
@reggi No problem. Hopefully it's useful to you :)
@sirlantis Any more feedback on this implementation so far?

**Comment by sirlantis** [comment]
@imjoshholloway I really like it. Just added two small notes but otherwise I'm awaiting your pull-request. :)

**Comment by imjoshholloway** [comment]
@sirlantis Thanks :+1: . Feedback applied and pull-request sent.

**Comment by imjoshholloway** [comment]
@sirlantis I think this can now be closed :+1:

**Comment by thardy** [comment]
How hard would it be to allow includes to draw from a predefined list of string based templates instead of looking at the file system?  I'm thinking of storing the templates in MongoDb, and generating from there.

**Comment by thardy** [comment]
Did some quick looking.  Would it just require a change to local_file_system.coffee?  Could I just change readTemplateFile to use my own mechanism?

I'm very new to nodejs and have no idea what the most elegant way to couple this to "my own mechanism" looks like though.

**Comment by sirlantis** [comment]
@imjoshholloway Closed now (since I just published it in 2.5.0).

**Comment by sirlantis** [comment]
@thardy Please take a look at https://github.com/sirlantis/liquid-node/blob/master/examples/custom_file_system.coffee

**Comment by thardy** [comment]
Thanks, that looks perfect.

**Comment by pongstr** [comment]
Hi thanks for this awesome feature! is this also documented somewhere? :+1:

**Comment by NPellet** [comment]
I don't know much about Liquid templating, but in Jekyll, one is allowed to pass parameters to the include tag to be recovered later in the included file. I haven't been able to make it work somehow. 

Is this covered by liquid-node ?

**Comment by sirlantis** [comment]
@NPellet See #37

**Comment by NPellet** [comment]
Yes I figured this out, thanks !

**Comment by randohinn** [comment]
Is  [josh's](https://github.com/sirlantis/liquid-node/issues/24#issuecomment-76677646) example the usage documentation for include currently? What about a way to have relative includes?
