### ISSUE TITLE
Ability to call method on object?

### ISSUE THREAD

**Issue by imjoshholloway** [sirlantis/liquid-node#30]
I've got a use-case where I'd like to be able to do something like this:

```
{% for page in pages.get() %}
    {{page.name}}
{% endfor %}
```

Where `pages.get()` returns a promise.

I've tried doing something like this to test it but it doesn't seem to work:

```javascript
var pages = {
    get: function () {
        return new Promise(function (resolve, reject) {
            setTimeout(function () {
                return resolve([{name: 'Page 1'}, { name: 'Page 2'}]);
            }, 5000);
        }
    }
};

return res.render('index', { pages: pages });
```

If I swap the context out for: `{ pages: pages.get() }` and replace the `pages.get()` call to just `pages` in the template it works as expected. Basically, I want to pass in an object that has methods to allow users to get certain types of page. E.g; `pages.mostViewed(10)` which would then do the query to get the top 10 most views pages etc.

Alternatively I'm going to need to write a custom tag which I'm keen to avoid as it means maintaining it separately.

Any thoughts / tips would be appreciated. Thanks

**Comment by imjoshholloway** [comment]
I've managed to get something along these lines working [here](https://github.com/imjoshholloway/liquid-node/commit/535bc8623f3580590fb512f787cd41954d0a724a).

One thing I'm not entirely comfortable with is whether or not there's any security implications with this approach. Especially since I actually had to modify one of the tests which "protects regular objects".

**Comment by pongstr** [comment]
:+1:

**Comment by joeldrapper** [comment]
:+1:

**Comment by sirlantis** [comment]
Sorry for not replying to this further.

I don't want to deviate from Liquid. The correct solution to doing this is to use Drops. Example in here:
https://github.com/sirlantis/liquid-node/blob/master/src/liquid/drop.coffee
