### ISSUE TITLE
bluebird should be a dependency, not a peerDependency

### ISSUE THREAD

**Issue by sfrdmn** [sirlantis/liquid-node#32]
Looking at [link](https://docs.npmjs.com/files/package.json#peerdependencies), it seems you really ought to express *bluebird* as a dependency of *liquid-node* rather than a peerDependency. If you're trying to spare people from requiring a project-wide dependency multiple times, you can recommend they use [dedupe](https://docs.npmjs.com/cli/dedupe). Using peerDependencies like this can [cause problems](https://github.com/npm/npm/issues/5080)

**Comment by dotnil** [comment]
If the parent module depends a version of bluebird that is not compliant with the one specified in node-liquid, then there will be a problem. 

Given that now Node has released version 4.x, both 0.12.x and 4.x have got a native Promise, I'd recommend change bluebird as peerDependency to native-or-bluebird as dependency.
