### ISSUE TITLE
How would I go about implementing layout functionality?

### ISSUE THREAD

**Issue by thardy** [sirlantis/liquid-node#33]
I've been tinkering with liquid-node, and I was wondering what the best way is to go about implementing "layout" functionality.

I'm thinking of the common CMS pattern where something like a blog post specifies a layout of 'defaultPost' and defaultPost looks like...

```
<header>I'm the header</header>
{% include "content???" %} <- this is where whatever specified this as their template gets their content inserted
<footer>I'm the footer</footer>
```

I figure I can somehow leverage the new include tag.  The problem comes from the fact that it's the child that is specifying it's parent layout.  The best I've come up with is to render the layout (not the child), supplying a model that is the original child model (whatever data it needs), plus a new property called "content", that is assigned the template/markup of the child.

```
engine.parseAndRender("layout", { <originalChildModelProperties>, content: childTemplate })
```

I haven't had a chance to try this yet, but it doesn't feel right to be manually building the model like that.  I'll definitely comment more once I've had a chance to try this out.

Is there a better approach to implement the concept of layouts before I get started?

**Comment by sirlantis** [comment]
- Take a look at jinja2's Block Assignments.
- Or Jade Extends http://jade-lang.com/reference/extends/

Something similar has been done in [assemble-liquid](https://github.com/sirlantis/assemble-liquid/blob/master/src/liquid-ext.coffee). The include-tag by itself is an inspiration for that but not the right tool. But you can copy a lot of code from there.
