### ISSUE TITLE
new Liquid.LocalFileSystem relativity?

### ISSUE THREAD

**Issue by randohinn** [sirlantis/liquid-node#49]
Where does `new Liquid.LocalFileSystem` resolve relative path's from? The folder of the .js file that its in, or the folder from where the nodejs app was started?

eg.. If i Have this kind of structure::

```
dir
   things
       thing-that-calls-a-function.js
       thing-that-calls-liquid.js
   themes
       xyz
          templates
              index.liquid
```

And I start my app with `node things/thing-that-calls-a-function.js`, and said file calls a function that runs a `new Liquid.LocalFileSystem` from the other js file, what would be the proper path to give to the `new Liquid.LocalFileSystem`  constructor to reach the templates folder correctly?

**Comment by sirlantis** [comment]
The `LocalFileSystem` can be seen as a reference implementation. It doesn't support relative paths, just a `root` path. You would configure it with `themes/xzy/template` as root.

**Comment by randohinn** [comment]
I can't seem to crack this trough... here's a more complete example:

```javascript
// Liquid => HTML
    renderPage: function(target_page) {
        console.log("Rendering "+target_page);
        engine.registerFileSystem(new Liquid.LocalFileSystem("themes/"+this.getActiveTheme()+"/templates/"));
       
        engine.fileSystem.readTemplateFile(target_page+".liquid").then(function (src) {
           console.log(engine.parseAndRender(src));
        });
    },

```

This is a function inside the above-referenced `thing-that-calls-liquid.js` It is passed a string `"index"` as `target_page.` The only output from this function that I get is the first `console.log` - `Rendering index`. Is there some edge case that I'm missing here?

**Comment by randohinn** [comment]
@sirlantis I got it to work with the following code, to the point where it tries to render... no string is returned from parseAndRender, though, therefore writPageFile does squat...... Why could that be?

```javascript
 // Liquid => HTML
    renderPage: function(target_page,site_dir) {
        console.log("Rendering "+target_page);
        engine.registerFileSystem(new Liquid.LocalFileSystem("themes/"+this.getActiveTheme()+"/templates/","liquid"));
       
        engine.fileSystem.readTemplateFile(target_page).then(function (src) {
           this.writePageFile(site_dir+"/"+target_page+".html",engine.parseAndRender(src))
        });
    },
```

**Comment by randohinn** [comment]
Fixed. writePageFile not being called was a nodejs thing. Got around it by setting node's `this` to a variable and calling `writePageFile` on that.
