### ISSUE TITLE
Add `syncRender` to synchronously render templates

### ISSUE THREAD

**Issue by subwiz** [sirlantis/liquid-node#50]
A synchronous API to render and get error would be helpful.

**Comment by sirlantis** [comment]
Hi @subwiz,

I see why such an API could be useful. However this library uses [Promises/A+](https://promisesaplus.com/) extensively at its core, especially relying on this behavior:

> 2.2.4 `onFulfilled` or `onRejected` must not be called until the execution context stack contains only platform code.

There's more elaboration on this in [this "Synchronous promise resolution" answer](http://stackoverflow.com/a/27971478/28401).

I don't see a way to add this feature in a maintainable fashion.

**Comment by subwiz** [comment]
Thanks for letting me know!
