### ISSUE TITLE
{%-  -%} syntax throws error

### ISSUE THREAD

**Issue by pavelloz** [sirlantis/liquid-node#64]
Correct liquid code (per https://help.shopify.com/themes/liquid/basics/whitespace ):

```
{%- assign test = 'test' -%}
```

Is throwing an error:

```
Tag '{%- assign test = 'test' -%}' was not properly terminated with regexp: undefined
    at {%- assign test = 'test' -%} (undefined:18:1)
```

**Comment by pavelloz** [comment]
Wrong project :)

**Comment by pavelloz** [comment]
Seems like i pasted it correctly by mistake :)

Here's investigation performed by @tomheller - https://github.com/tomheller/liquid-linter/issues/3

**Comment by scottge** [comment]
Is this issue resolved?
